### ISSUE TITLE
Länka CONTRIBUTING.md från index

### ISSUE THREAD

**Issue by felixmulder** [datateknik-lth/datateknik-lth.github.io#1]
Som ni säkert har sett så har branchen "middleman" försvunnit från datateknik-lth-repot. Detta är för att kunna ha det som organisations-sida istället. Detta ger oss en mycket trevligare länk: https://datateknik-lth.github.io

Det hade varit bra ifall någon som är ett större fan av ruby kunde tänka sig länka till CONTRIBUTING.md från index.  nudge @Dracyr 

Skillnaden mellan den gamla lösningen och den nya är att middleman deployar till master, medan materialet för att generera sidan ligger i branchen "site".

cc @datateknik-lth/owners @datateknik-lth/writers

**Comment by Dracyr** [comment]
Will do när jag är tillbaka i lund igen efter helgen!
