### ISSUE TITLE
Eva Tardos Book Solution link not working

### ISSUE THREAD

**Issue by sumollodha** [datateknik-lth/datateknik-lth.github.io#3]
Following link is not working:
https://github.com/datateknik-lth/datateknik-lth/tree/master/EDAN55-advalg/Algorithm%20Design%20(Kleinberg%20Tardos%202005)%20-%20Solutions/Algorithm%20Design%20-%20Kleinberg%20%26%20Tardos%20-%20Solutions

Here is the screenshot
![image](https://cloud.githubusercontent.com/assets/3978938/10694435/123f60d6-796c-11e5-8074-b73966591e6e.png)

Can you get this up running. It was quite useful, as I am stuck while solving some problems.
Thanks.

**Comment by felixmulder** [comment]
These have been removed by demand of the author.

**Comment by sumollodha** [comment]
Hi,
    Thanks for the reply. Can you just send the me the solutions via google
drive or email, so that I can download on my system once. I am in middle of
solving the exercises but no reference to look upon. My email is
sumollodha@gmail.com.

Thanks,
Sumol
